oracle_dbt:
  outputs:
    dev:
      type: oracle
      user: "{{ env_var('DBT_ORACLE_USER') }}"
      pass: "{{ env_var('DBT_ORACLE_PASSWORD') }}"
      tns_name: "{{ env_var('DBT_ORACLE_TNS_NAME') }}"
      schema: "{{ env_var('DBT_ORACLE_SCHEMA') }}"
      threads: 4
  verify_ssl: false
  target: dev
