version: 2

sources:
  - name: FAWDBTCORE
    config:
      materialized: incremental
      
    tables:
      - name: web_events
      - name: mobile_events
      - name: raw_users
      - name: web_order_info
      

